name: UMU RPM Build - Fedora/Nobara 40

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
      shasum:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:40

    steps:
      - name: Install Git
        run: dnf install -y git

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Install build dependencies
        run: dnf install -y rpm-build meson ninja-build cmake g++ gcc-c++ scdoc git python3-devel python3-build python3-installer python3-hatchling python python3 cargo python3-hatch-vcs python3-wheel libzstd-devel

      - name: Extract Version and SHA
        run: |
          # Get version from git tags (assuming semantic versioning format)
          VERSION=$(git describe --tags --abbrev=0 || echo "unknown")

          # Get current commit SHA
          COMMIT_SHA=$(git rev-parse HEAD)

          # Store values in environment file
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV

      - name: Build the project
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          git submodule update --init --recursive
          cd ..
          mkdir -p ~/rpmbuild/SOURCES/
          cp -R umu-launcher umu-launcher-$VERSION/
          tar -cvzf umu-launcher-$VERSION.tar.gz umu-launcher-$VERSION
          mv umu-launcher-$VERSION.tar.gz ~/rpmbuild/SOURCES/
          rm -Rf umu-launcher-$VERSION/
          cd umu-launcher/

          # Use either provided input or extracted value
          VERSION=${VERSION}
          COMMIT_SHA=${COMMIT_SHA}

          echo $VERSION
          sed -i 's/%global tag/%global tag '"$VERSION"'/' packaging/rpm/umu-launcher.spec
          cat packaging/rpm/umu-launcher.spec | grep tag

          echo $COMMIT_SHA
          sed -re '/^#%global manual_commit/s|^# ?(.*)|\1|' packaging/rpm/umu-launcher.spec -i
          sed -i 's/%global manual_commit/%global manual_commit '"$COMMIT_SHA"'/' packaging/rpm/umu-launcher.spec
          cat packaging/rpm/umu-launcher.spec | grep manual_commit

          rpmbuild -ba packaging/rpm/umu-launcher.spec
          mv ~/rpmbuild/RPMS/x86_64/umu-launcher-$VERSION*.rpm \
             ~/rpmbuild/RPMS/x86_64/umu-launcher-$VERSION.fc40.rpm

      - name: Fedora-40
        uses: actions/upload-artifact@v4
        with:
          name: umu-launcher-${{ env.VERSION }}.fc40.rpm
          path: ~/rpmbuild/RPMS/x86_64/umu-launcher-${{ env.VERSION }}.fc40.rpm
