name: Create Release

on:
  release:
    types: [published]  # Trigger when a new release is published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Debian 12 Artifact
        uses: actions/download-artifact@v3
        with:
          name: Debian-12

      - name: Download Ubuntu 24 Artifact
        uses: actions/download-artifact@v3
        with:
          name: Ubuntu-24

      - name: Download Fedora RPM Artifact
        uses: actions/download-artifact@v3
        with:
          name: umu-launcher-rpm

      - name: Download Zipapp Artifact
        uses: actions/download-artifact@v3
        with:
          name: Zipapp

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.release.tag_name }}
          release_name: ${{ github.event.release.name }}
          draft: false
          prerelease: false

      - name: Upload Debian 12 Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: results/*.deb
          asset_name: Debian-12.deb
          asset_content_type: application/octet-stream

      - name: Upload Ubuntu 24 Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: results/*.deb
          asset_name: Ubuntu-24.deb
          asset_content_type: application/octet-stream

      - name: Upload Fedora RPM Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ~/rpmbuild/RPMS/noarch/*.rpm
          asset_name: umu-launcher-rpm.rpm
          asset_content_type: application/octet-stream

      - name: Upload Zipapp Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: results/umu-run
          asset_name: umu-run.zip
          asset_content_type: application/octet-stream
